@startuml

class User {
  - id: int
  - username: string
  - email: string
  - password: string
  - confirmAccount : string
  - roles : string
}

class Article {
  - id: int
  - title: string
  - content: string
  - publishedAt: datetime
  - author: User
}

class Comment {
  - id: int
  - content: string
  - postedAt: datetime
  - article: Article
  - author: User
}

User --> "*" Article
Article --> "*" Comment
Comment --> User

@enduml
